Feat/generators
FlowSquad/miranum-ide pull request #57
Opened 2023-01-24 09:45 UTC by J-Mertl

**Issue**
https://www.notion.so/miragon/Miranum-Console-Naming-verbessern-d2633710796d40678b3113bc5c1c3589
and https://www.notion.so/miragon/Miranum-Console-Naming-verbessern-d2633710796d40678b3113bc5c1c3589

**Checklist**

* Code is easy to understand
* No obvious errors or bugs
* CI/CD Pipelines did run successfully
* Tests were implemented
* Documentation was created

2023-01-24 12:42 UTC, lmoesle requested changes

2023-01-24 12:42 UTC, lmoesle commented on miranum.json
> +    "configs": { "path": "configs", "extension": ".config" }
Als default für die Configs bitte nicht `.config` verwenden, nachdem das eigentlich eine Standardkonvention (für nicht json Configs) ist. Ich würde erstmal `.config.json` verwenden.

2023-01-24 12:42 UTC, lmoesle commented on resources/my-process-automation-project/miranum.json
> +    "configs": { "path": "configs", "extension": ".config" }
Als default für die Configs bitte nicht `.config` verwenden, nachdem das eigentlich eine Standardkonvention (für nicht json Configs) ist. Ich würde erstmal `.config.json` verwenden.

2023-01-24 12:42 UTC, lmoesle commented on libs/miranum-core/src/lib/miranum-core.spec.ts
> +    configs: { path: "configs", extension: ".config" }
Als default für die Configs bitte nicht `.config` verwenden, nachdem das eigentlich eine Standardkonvention (für nicht json Configs) ist. Ich würde erstmal `.config.json` verwenden.

2023-01-24 12:42 UTC, lmoesle commented on libs/miranum-core/src/lib/generate/plugins.ts
> +    "configs": { "path": "configs", "extension": ".config" }
Als default für die Configs bitte nicht `.config` verwenden, nachdem das eigentlich eine Standardkonvention (für nicht json Configs) ist. Ich würde erstmal `.config.json` verwenden.

2023-01-24 12:42 UTC, lmoesle commented on apps/miranum-cli/src/app/deployment/deployment.ts
> +                    (await getFiles(`${path}/${workspace[key]}`.replace("//", "/"), [this.digiwfLib.projectConfig?.workspace.forms.extension]))
Der Workspace war bisher als type `object` in der MiranumConfig definiert.  Bisher war das ja nur ein einfaches Json Object.
Jetzt geben wir eine ganze Struktur für den Workspace vor. Dementsprechend sollte der Type des Workspaces auch geändert werden (bzw. es macht Sinn einen richtigen Typen dafür zu definieren).

2023-01-24 12:42 UTC, lmoesle commented on libs/miranum-core/src/lib/miranum-core.ts
> +        if(this.projectConfig?.workspace[this.camelize(`${type}s`)] && lastFolder === projectName) {
In der generate Domain fehlen aktuell noch die Dateiendungen. Wenn die Config gesetzt ist sollen die Dateiendungen aus der Config genommen werden, sonst ein default.

2023-01-26 12:14 UTC, lmoesle requested changes

2023-01-26 12:14 UTC, lmoesle commented on libs/miranum-core/src/lib/miranum-core.ts
> +                pathInProject = workspace.path;
Bitte die ganzen Github Actions warnings fixen

2023-01-26 12:14 UTC, lmoesle commented on libs/miranum-core/src/lib/miranum-core.ts
> +                extension = workspace.extension;
auch hier warnings fixen

2023-01-27 06:46 UTC, J-Mertl commented on apps/miranum-cli/src/app/deployment/deployment.ts
> +        (await getFiles(path, ".bpmn"))
Find ich nicht, weil es geht ja genau darum bpmn und dmns erstellen und modellieren zu können, mit allen hilfsmitteln die wir providen. Wenn die zwei in die workspace aufgenommen werden, kann der user die ja entfernen, auch die extension macht da keinen sinn, weil die ja nen standard haben

2023-01-27 07:12 UTC, lmoesle commented on apps/miranum-cli/src/app/deployment/deployment.ts
> +        (await getFiles(path, ".bpmn"))
Ich finde schon das die bpmns und dmns in die miranum.json mit reinsollten. Dann kann der User auch Prozesse und DMN Tabellen in Ordner verschieben.
Die Fileextension zu ändern oder bpmn wegzulassen macht wenig Sinn, aber das werden die User schon nicht machen und wenn doch dann ist es ein Problem des Users.

2023-01-27 15:15 UTC, lmoesle approved these changes

2023-01-30 06:42 UTC, merged